# Generated by Django 2.0.8 on 2018-08-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='sentences',
            field=models.BigIntegerField(default=0),
        ),
    ]
