# Generated by Django 2.0.8 on 2018-08-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0002_note_sentences'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='no title', max_length=100),
        ),
    ]
