# Generated by Django 2.0.8 on 2018-08-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0004_auto_20180825_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
