# Generated by Django 2.0.8 on 2018-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0005_auto_20180827_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='words',
            field=models.BigIntegerField(default=0),
        ),
    ]
