# Generated by Django 2.0.8 on 2018-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0006_note_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='hook',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
