# Generated by Django 2.0.8 on 2018-09-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0008_auto_20180904_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='hook',
        ),
    ]
