# Generated by Django 2.0.8 on 2018-09-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0010_note_hook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='hook',
            field=models.CharField(max_length=20),
        ),
    ]
