# Generated by Django 2.0.8 on 2018-09-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0011_auto_20180904_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='hook',
        ),
    ]
