# Generated by Django 2.0.8 on 2018-09-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0012_remove_note_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='hook',
            field=models.CharField(default='', max_length=20),
        ),
    ]
